stock_index: null
time_frequency: 1d
include_sentiments: null
modelling:
  evaluation_metric: null
  target: "return"
  training_size: 378 # 252 * 1.5
  validation_size: 63 # 252 / 4
  max_number_lags: 12
  random_state: 2024